# Generated by Django 4.2 on 2025-10-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_file_is_trashed_file_shared_with_file_trashed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
