# Generated by Django 4.2 on 2025-10-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_folder_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
