# Generated by Django 4.2 on 2025-10-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_folder_is_trashed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='file',
            name='trashed_at',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='is_starred',
        ),
    ]
