# Generated by Django 4.2 on 2025-10-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_remove_file_shared_with_remove_file_trashed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='is_trashed',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='is_trashed',
        ),
        migrations.AddField(
            model_name='folder',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
