# Generated by Django 4.2 on 2025-11-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_subscription_plans_data'),
        ('storage', '0008_subscriptionplan_usersubscription'),
    ]

    operations = [
    ]
